"""Added new models

Revision ID: cdec070e3fd3
Revises: ffdc0a98111c
Create Date: 2021-01-26 10:30:09.497175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdec070e3fd3'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('quizzes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('hashed_password', sa.String(
                        length=255), nullable=True),
                    sa.Column('is_private', sa.Boolean(), nullable=True),
                    sa.Column('question_quantity',
                              sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['category_id'], ['categories.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('questions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('question_number', sa.Integer(), nullable=False),
                    sa.Column('body', sa.String(length=260), nullable=False),
                    sa.Column('question_type', sa.String(
                        length=50), nullable=False),
                    sa.Column('answer_1', sa.String(
                        length=100), nullable=False),
                    sa.Column('answer_2', sa.String(
                        length=100), nullable=False),
                    sa.Column('answer_3', sa.String(
                        length=100), nullable=False),
                    sa.Column('answer_4', sa.String(
                        length=100), nullable=False),
                    sa.Column('correct_answer', sa.Integer(), nullable=True),
                    sa.Column('quiz_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('scores',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('quiz_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('questions')
    op.drop_table('quizzes')
    op.drop_table('categories')
    # ### end Alembic commands ###
