"""Added new models - correct quiz model

Revision ID: 687f0f9a1b31
Revises: cdec070e3fd3
Create Date: 2021-01-26 11:31:15.949807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687f0f9a1b31'
down_revision = 'cdec070e3fd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
