"""empty message

Revision ID: 930833c3caaf
Revises: 687f0f9a1b31
Create Date: 2021-01-26 12:05:51.633349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930833c3caaf'
down_revision = '687f0f9a1b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quizzes', 'hashed_password',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quizzes', 'hashed_password',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    # ### end Alembic commands ###
