"""empty message

Revision ID: f20f93b16104
Revises: 012420e23484
Create Date: 2021-01-29 18:41:05.086707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f20f93b16104'
down_revision = '012420e23484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('questions', 'correct_answer',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               nullable=False)
    op.drop_column('questions', 'answer_4')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('answer_4', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('questions', 'correct_answer',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('categories', 'name',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
