"""empty message

Revision ID: a818ff8903c5
Revises: f20f93b16104
Create Date: 2021-01-29 18:42:35.641444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a818ff8903c5'
down_revision = 'f20f93b16104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'question_type',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'question_type',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=False)
    # ### end Alembic commands ###
